version: '3.8'

services:
  db:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${POSTGRES_DB} 
    secrets:
      - db_user
      - db_password
    networks:
      - happy-town-network

  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: don-sbn@hotmail.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pg_password
      PGADMIN_LISTEN_PORT: 80
    secrets:
      - pg_password
    ports:
      - 15432:80
    depends_on:
      - db
    networks:
      - happy-town-network

secrets:
  db_user:
    file: db_user.txt
  db_password:
    file: db_password.txt
  pg_password:
    file: pg_password.txt

networks:
  happy-town-network:
    name: happy-town-network
    driver: bridge